---
- name: "Apply base configuration to the server(s)"
  hosts: all
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - base

- name: "Configure and deploy database"
  hosts: database
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - database

- name: "Configure and deploy message queue"
  hosts: queue
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - queue

# - name: "Configure and deploy worker(s)"
#   hosts: worker
#   vars_files:
#     - "{{ environment_vars }}"
#   roles:
#     - worker

- name: "Configure and deploy the webapp"
  hosts: webapp
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - app

- name: "Configure and nginx reverse proxy for the webapp"
  hosts: webapp
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - role: web
      vars:
        name: app
        domain: "{{ app_domain }}"
        dir:  "/home/{{ ansible_user }}/webapp"

- name: "Configure and deploy api"
  hosts: webapi
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - api

- name: "Configure and nginx reverse proxy for the API"
  hosts: webapi
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - role: web
      vars:
        name: api
        domain: "{{ api_domain }}"

- name: "Configure and nginx reverse proxy for the model store"
  hosts: webapi
  vars_files:
    - "{{ environment_vars }}"
  roles:
    - role: web
      vars:
        name: model_store
        domain: "{{ model_store_domain }}"
