---
root_dir: "/home/{{ ansible_user }}"
app_dir: "{{ root_dir }}/webapp"
app_virtualenv_dir: "{{ app_dir }}/venv"
app_repo: ssh://git@github.com/scancer-org/webapp.git
app_wsgi: config
env_vars: {
  WEB_CONCURRENCY: "{{ ansible_processor_vcpus*2 }}",
  DJANGO_SETTINGS_MODULE: "config.settings.{{ app_env }}",
  DJANGO_SECRET_KEY: "{{ app_secret_key }}",
  DJANGO_ALLOWED_HOSTS: "{{ app_domain }}",
  DJANGO_ADMIN_URL: "backend",
  DATABASE_URL: "postgres://{{ db_user }}:{{ db_password }}@{{ hostvars[groups['database'][0]].ansible_default_ipv4.address }}:{{ db_port }}/{{ db_name }}",
  REDIS_URL: "redis://todo/",
  CELERY_BROKER_URL: "todo",
}
